# Generated by Django 2.0.2 on 2018-02-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date added')),
                ('desc', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcare.Car')),
            ],
        ),
    ]
