# Generated by Django 2.0.2 on 2018-02-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='desc',
        ),
    ]
