# Generated by Django 2.0.2 on 2018-02-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0004_auto_20180220_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date added')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcare.Car')),
            ],
        ),
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(verbose_name='date added'),
        ),
    ]
