# Generated by Django 2.0.2 on 2018-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0005_auto_20180220_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='initial'),
            preserve_default=False,
        ),
    ]
